name: Android

on:
  push:
    branches:
      - master
      - developer
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
            node-version: 14.x
 

      - run: ci=false && npm ci && npx jetify
      - run: chmod +x ./gradlew && ./gradlew assembleDebug -Dorg.gradle.logging.level=info
        working-directory: android
        name: Build Android APK (debug)
